logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
spring:
    datasource:
        url: jdbc:mysql://db:3306/todo_docker?useSSL=false
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
